format = """
λ\
$directory\
$git_branch\
$git_status\
$nodejs\
$rust\
$golang\
$php\
$time\
\n$character"""

[directory]
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

[directory.substitutions]
"Documents" = "文件"
"Downloads" = "下载"
"Music" = "音乐"
"Pictures" = " "
"roy" = "家"

[git_branch]
symbol = ""

[nodejs]
symbol = ""

[rust]
symbol = ""

[golang]
symbol = "Go"

[time]
disabled = true
time_format = "%R" # Hour:Minute Format
format = '[[  $time ]]'


